# What is a neural network

Neural network is a collection of neurons that are connected by layers. Each neuron is a small
computing unit that performs simple calculations to collectively solve a problem. They are 
organized in layers. There are 3 types of layers: input layer, hidden layer and 
outter layer.  Each layer contains a number of neurons, except for the input layer. Neural networks mimic the way a human brain processes information.

<img alt="Diagram showing different types of layers in a neural network" src="images/4-model-1.png" />

## Components of a neural network

- **Activation function** determines whether a neuron should be activated or not. The computations that happen in a neural network include applying an activation function. If a neuron activates, then it means the input is important.  The are different kinds of activation functions. The choice of which activation function to use depends on what you want the output to be. Another important role of an activation function is to add non-linearity to the model.
    - _Binary_ used to set an output node to 1 if function result is positive and 0 if the function result is negative. $f(x)= {\small \begin{cases} 0, & \text{if } x < 0\\ 1, & \text{if } x\geq 0\\ \end{cases}}$
    - _Sigmod_ is used to predict the probability of an output node being between 0 and 1.  $f(x) = {\large \frac{1}{1+e^{-x}}} $
    - _Tanh_ is used to predict if an output node is between 1 and -1.  Used in classification use cases.  $f(x) = {\large \frac{e^{x} - e^{-x}}{e^{x} + e^{-x}}} $
    - _ReLU_ used to set the output node to 0 if fuction result is negative and keeps the result value if the result is a positive value.  $f(x)= {\small \begin{cases} 0, & \text{if } x < 0\\ x, & \text{if } x\geq 0\\ \end{cases}}$
- **Weights** influence how well the output of our network will come close to the expected output value. As an input enters the neuron, it gets multiplied by a weight value and the resulting output is either observed, or passed to the next layer in the neural network. Weights for all neurons in a layer are organized into one tensor
- **Bias** makes up the difference between the activation function's output and its intended output. A low bias suggest that the network is making more assumptions about the form of the output, whereas a high bias value makes less assumptions about the form of the output. 

<img alt="Diagram showing neural computation" src="images/4-model-2.png" />

We can say that an output $y$ of a neural network layer with weights $W$ and bias $b$ is computed as summation of the inputs multiply by the weights plus the bias $x = \sum{(weights * inputs) + bias} $, where $f(x)$ is the activation function.

# Build a neural network

Neural networks are comprised of layers/modules that perform operations on data. 
The `torch.nn` namespace provides all the building blocks you need to 
build your own neural network. Every module in PyTorch subclasses the `nn.Module`. 
A neural network is a module itself that consists of other modules (layers). This nested structure allows for
building and managing complex architectures easily.

In the following sections, we'll build a neural network to classify images in the FashionMNIST dataset.

In [1]:
%matplotlib inline
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

## Get a hardware device for training

We want to be able to train our model on a hardware accelerator like the GPU, if it is available. Let's check to see if 
`torch.cuda` is available, else we continue to use the CPU.

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('Using {} device'.format(device))

Using cpu device


## Define the class

We define our neural network by subclassing `nn.Module`, and 
initialize the neural network layers in `__init__`. Every `nn.Module` subclass implements
the operations on input data in the `forward` method.

Our neural network are composed of the following:
- The input layer with 28x28 or 784 features/pixels.
- The first linear module takes the input 784 features and transforms it to a hidden layer with 512 features
- The ReLU activation function will be applied in the transformation
- The second linear module take 512 features as input from the first hidden layer and transforms it to the next hidden layer with 512 features
- The ReLU activation function will be applied in the transformation
- The third linear module take 512 features as input from the second hidden layer and transforms it to the output layer with 10, which is the number of classes
- The ReLU activation function will be applied in the transformation

In [3]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
            nn.ReLU()
        )

    def forward(self, x):
        x = self.flatten(x) # Flatten the input tensor 
        logits = self.linear_relu_stack(x)
        return logits

#### ravel is faster than flatten(in numpy)

In [5]:
import time
import numpy as np
import matplotlib.pyplot as plt


In [15]:
t1 = time.time()
tmpx = np.random.rand(100, 28, 28)
tmpx = tmpx.flatten()
t2 = time.time()
print(t2-t1) # 0.0019919872283935547

0.0010006427764892578


In [9]:
tmpx.shape # (78400,)

(78400,)

In [14]:
t3 = time.time()
tmpx = np.random.rand(100, 28, 28)
tmpx = tmpx.ravel()
t4 = time.time()
print(t4-t3) # 0.0009984970092773438

0.0010006427764892578


We create an instance of `NeuralNetwork`, and move it to the `device`, and print 
it's structure.



In [16]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
    (5): ReLU()
  )
)


To use the model, we pass it the input data. This executes the model's `forward`, along with some background operations. However, do not call `model.forward()` directly! Calling the model on the input returns a 10-dimensional tensor with raw predicted values for each class.

We get the prediction densities by passing it through an instance of the `nn.Softmax`.

In [18]:
X = torch.rand(1, 28, 28, device=device)
logits = model(X) 
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")

Predicted class: tensor([6])


## Weight and Bias


The `nn.Linear` module randomly initializes the ${weights}$  and ${ bias}$ for each layer and internally stores the values in Tensors.

In [19]:
print(f"First Linear weights: {model.linear_relu_stack[0].weight} \n")

print(f"First Linear weights: {model.linear_relu_stack[0].bias} \n")

First Linear weights: Parameter containing:
tensor([[ 0.0096, -0.0102,  0.0099,  ...,  0.0024, -0.0043,  0.0204],
        [-0.0353, -0.0278, -0.0143,  ...,  0.0339, -0.0234, -0.0098],
        [-0.0252,  0.0325,  0.0079,  ...,  0.0259, -0.0111, -0.0140],
        ...,
        [-0.0282, -0.0200, -0.0025,  ...,  0.0085,  0.0038, -0.0240],
        [ 0.0223,  0.0301,  0.0148,  ...,  0.0007,  0.0250, -0.0130],
        [ 0.0233, -0.0033,  0.0223,  ...,  0.0166, -0.0252,  0.0297]],
       requires_grad=True) 

First Linear weights: Parameter containing:
tensor([ 0.0078,  0.0231,  0.0189, -0.0354,  0.0065,  0.0342, -0.0221, -0.0148,
         0.0256, -0.0273, -0.0304,  0.0078, -0.0140,  0.0046, -0.0263,  0.0242,
        -0.0164,  0.0084,  0.0301,  0.0006, -0.0282, -0.0231, -0.0162, -0.0147,
        -0.0338, -0.0116,  0.0345, -0.0044, -0.0138,  0.0297,  0.0235, -0.0162,
        -0.0252,  0.0033,  0.0349,  0.0269, -0.0054, -0.0223, -0.0321,  0.0082,
         0.0167,  0.0227, -0.0207,  0.0190, -0.02

## Model layers

Let's break down the layers in the FashionMNIST model. To illustrate it, we 
will take a sample minibatch of 3 images of size **28x28** and see what happens to it as 
we pass it through the network. 

In [20]:
input_image = torch.rand(3,28,28)
print(input_image.size())

torch.Size([3, 28, 28])


### nn.Flatten

We initialize the `nn.Flatten` layer to convert each 2D 28x28 image into a contiguous array of 784 pixel values (the minibatch dimension (at dim=0) is maintained). Each of the pixels are pass to the input layer of the neural network.  

<img alt="Diagram showing how pixels in image are flatten" src="images/4-model-3.png" />

In [21]:
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

torch.Size([3, 784])


### nn.Linear 

The linear layer is a module that applies a linear transformation on the input using it's stored weights and biases.  The gayscale value of each pixel in the input layer will be connected to neurons in the hidden layer for calculation.    The calculation used for the transformation is ${{weight * input + bias}} $.


In [22]:
layer1 = nn.Linear(in_features=28*28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())

torch.Size([3, 20])


### nn.ReLU

Non-linear activations are what create the complex mappings between the model's inputs and outputs.
They are applied after linear transformations to introduce *nonlinearity*, helping neural networks
learn a wide variety of phenomena. In this model, we use `nn.ReLU` between our linear layers, but there's other activations to introduce non-linearity in your model.

The ReLU activation function takes the output from the linear layer calculation and replaces the negative values with zeros.

Linear output: ${ x = {weight * input + bias}} $.  
ReLU:  $f(x)= 
\begin{cases}
    0, & \text{if } x < 0\\
    x, & \text{if } x\geq 0\\
\end{cases}
$

In [23]:
print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}")

Before ReLU: tensor([[ 0.2475,  0.1324, -0.2333,  0.2124, -0.1718, -0.3042,  0.0369, -0.0405,
         -0.1893, -0.1181, -0.5519, -0.5084,  0.0234, -0.2365, -0.5087, -0.1989,
          0.8105,  0.1982,  0.7474,  0.1900],
        [ 0.0238,  0.2330, -0.2761,  0.5029, -0.1057, -0.2556,  0.1678, -0.0408,
         -0.8124,  0.1149, -0.1198, -0.1466,  0.2672, -0.4059, -0.4988,  0.0644,
          0.9719,  0.4548,  0.5187, -0.0859],
        [ 0.3287, -0.0057, -0.3548,  0.0370, -0.0012, -0.1089,  0.0615, -0.5090,
         -0.3535,  0.0042, -0.2554, -0.4873,  0.1898, -0.1893, -0.0413, -0.0229,
          0.5757,  0.2615,  0.7095,  0.4245]], grad_fn=<AddmmBackward0>)


After ReLU: tensor([[0.2475, 0.1324, 0.0000, 0.2124, 0.0000, 0.0000, 0.0369, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0234, 0.0000, 0.0000, 0.0000, 0.8105, 0.1982,
         0.7474, 0.1900],
        [0.0238, 0.2330, 0.0000, 0.5029, 0.0000, 0.0000, 0.1678, 0.0000, 0.0000,
         0.1149, 0.0000, 0.0000, 0.2672, 0.0000, 0.00

### nn.Sequential

`nn.Sequential` is an ordered 
container of modules. The data is passed through all the modules in the same order as defined. You can use
sequential containers to put together a quick network like `seq_modules`.

In [24]:
seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
)
input_image = torch.rand(3,28,28)
logits = seq_modules(input_image)

### nn.Softmax

The last linear layer of the neural network returns `logits` - raw values in \[`-infty`, `infty`], which are passed to the
`nn.Softmax` module. The Softmax activation function is used to calculate the probability of the output from the neural network.  It is only used on the output layer of a neural network.  The results are scaled to values \[0, 1\] representing the model's predicted densities for each class. `dim` parameter indicates the dimension along which the result values must sum to 1.  The node with the highest probability predicts the desired output.

<img alt="Diagram shows softmax formula" src="images/4-model-4.png" />

In [25]:
softmax = nn.Softmax(dim=1)
pred_probab = softmax(logits)

In [26]:
pred_probab

tensor([[0.1120, 0.1095, 0.0907, 0.1107, 0.0936, 0.0748, 0.1199, 0.0968, 0.0819,
         0.1102],
        [0.1224, 0.1242, 0.0853, 0.1042, 0.0967, 0.0681, 0.1087, 0.1019, 0.0792,
         0.1094],
        [0.1001, 0.1167, 0.0986, 0.1229, 0.0919, 0.0644, 0.1355, 0.0929, 0.0776,
         0.0994]], grad_fn=<SoftmaxBackward0>)

## Model parameters

Many layers inside a neural network are *parameterized*, i.e. have associated weights 
and biases that are optimized during training. Subclassing `nn.Module` automatically 
tracks all fields defined inside your model object, and makes all parameters 
accessible using your model's `parameters()` or `named_parameters()` methods.

In this example, we iterate over each parameter, and print its size and a preview of its values.


In [27]:
print("Model structure: ", model, "\n\n")

for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")

Model structure:  NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
    (5): ReLU()
  )
) 


Layer: linear_relu_stack.0.weight | Size: torch.Size([512, 784]) | Values : tensor([[ 0.0096, -0.0102,  0.0099,  ...,  0.0024, -0.0043,  0.0204],
        [-0.0353, -0.0278, -0.0143,  ...,  0.0339, -0.0234, -0.0098]],
       grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.0.bias | Size: torch.Size([512]) | Values : tensor([0.0078, 0.0231], grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.2.weight | Size: torch.Size([512, 512]) | Values : tensor([[ 0.0215,  0.0081,  0.0100,  ..., -0.0032, -0.0345,  0.0072],
        [-0.0225, -0.0157,  0.0368,  ...,  0.0036,  0.0117,  0.0247]],
       grad_fn=<SliceBackward0>) 

Layer: linear_relu

--------------


